function gm = calculate_global_measures(A, A_orig, type)
%CALCULATE_GLOBAL_MEASURES calculates the global measures of graph A and
%returns all these in a struct extending the GM
measures = {
    'assortativity_in_in.m',...
    'assortativity_in_out.m',...
    'assortativity_out_in.m',...
    'assortativity_out_out.m',...
    'pathlength_wsg.m',...
    'pathlength_wsg_in.m',...
    'pathlength_wsg_out.m',...
    'clustering_nodal.m',...
    'degree.m',...
    'degree_in.m',...
    'degree_out.m',...
    'global_efficiency.m',...
    'global_efficiency_in.m',...
    'global_efficiency_out.m',...
    'transitivity'};
out_var = {
    'ass_in_in',...
    'ass_in_out',...
    'ass_out_in',...
    'ass_out_out',...         
    'pl_wsg',...
    'pl_wsg_in',...
    'pl_wsg_out',...
    'clustering_nodal',...
    'degree',...
    'degree_in',...
    'degree_out',...
    'gleff',...
    'gleff_in',...
    'gleff_out',...
    'trans'};

gm = struct();
n_measures = size(measures,2);
% Evaluate all measures
for i = 1:n_measures
    func = strrep(measures{i}, '.m', '');
    if isequal(measures{i}, 'validate_randomization')
        eval(sprintf('gm.%s = full(%s(A, A_orig));', out_var{i}, func))
    else
        eval(sprintf('gm.%s = full(%s(A, type));', out_var{i}, func))
    end
end
end

